name: Sorun Avcısı

# Bu iş akışı sadece manuel olarak çalıştırılabilir.
on:
  workflow_dispatch:

jobs:
  debug-run:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Betiği Çalıştır (Hata durumunda devam et)
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        # Bu adım hata verse bile, iş akışı durmayacak ve sonraki adıma geçecek.
        continue-on-error: true
        run: python "MAU_Rehber - GITHUB.py"
      
      # EN ÖNEMLİ ADIM
      - name: Tüm Teşhis Dosyalarını Yükle
        # Bu adım, bir önceki adım başarılı da olsa, başarısız da olsa HER ZAMAN çalışır.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hata-teshis-dosyalari
          # Klasördeki tüm .png ve .html dosyalarını yükle
          path: |
            *.png
            *.html
          if-no-files-found: ignore
