name: Personel Rehber Kontrolü

on:
  schedule:
    - cron: '10 9 * * 1-5'  # Hafta içi sabah 12:10 (TR)
    - cron: '10 15 * * 1-5'  # Hafta içi akşam 18:10 (TR)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: Önceki Veriyi Cache'den Geri Yükle
        uses: actions/cache@v4
        id: personel-cache
        with:
          path: rehber_durumu.csv
          key: ${{ runner.os }}-personel-${{ hashFiles('mau_rehber.py') }}
          restore-keys: |
            ${{ runner.os }}-personel-

      - name: Cache Durumunu Kontrol Et
        id: cache-check
        run: |
          if [ -f "rehber_durumu.csv" ]; then
            echo "cache-hit=true" >> $GITHUB_OUTPUT
          else
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli Paketleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Betiği Çalıştır
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          CACHE_HIT: ${{ steps.cache-check.outputs.cache-hit }}
        run: python mau_rehber.py

      - name: Yeni Veriyi Kaydet
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: personel-verisi
          path: rehber_durumu.csv
          retention-days: 7
