name: Personel Rehber Kontrolü

on:
  schedule:
    # Pazartesi-Cuma, sabah 09:00 (Türkiye saatiyle) çalışır.
    # (06:00 UTC)
    - cron: '0 6 * * 1-5'
    
    # Pazartesi-Cuma, sabah 10:40 (Türkiye saatiyle) çalışır.
    # (07:40 UTC)
    - cron: '40 7 * * 1-5'

    # Pazartesi-Cuma, akşam 18:00 (Türkiye saatiyle) çalışır.
    # (15:00 UTC)
    - cron: '0 15 * * 1-5'
    
  workflow_dispatch:
    # Bu satır, "Actions" sekmesinden manuel olarak çalıştırmanıza olanak tanır.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      # --- DEĞİŞİKLİK BURADA: ARTIFACT YERİNE CACHE KULLANILIYOR ---
      - name: Önceki Veriyi Cache'den Geri Yükle
        # Bu adım, 'personel-veri-cache' adında bir önbellek arar
        # ve bulursa içindeki 'rehber_durumu.csv' dosyasını geri yükler.
        uses: actions/cache@v4
        id: cache-personel-veri
        with:
          path: rehber_durumu.csv
          key: personel-veri-cache-v1

      - name: Dosyaları Listele (Cache Sonrası)
        run: ls -l

      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Betiği Çalıştır
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: python "mau_rehber.py"
      
      # Not: Cache sistemi, 'rehber_durumu.csv' dosyasında bir değişiklik
      # olduğunda, iş akışı sonunda otomatik olarak güncel halini kaydeder.
      # Ayrı bir yükleme adımı gerekmez.
