jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: Önceki Veriyi Cache'den Geri Yükle
        uses: actions/cache@v4
        id: cache-personel-veri
        with:
          path: rehber_durumu.csv
          key: ${{ runner.os }}-personel-veri-${{ hashFiles('MAU_Rehber - GITHUB.py') }}
          restore-keys: |
            ${{ runner.os }}-personel-veri-

      - name: Cache Durumunu Kontrol Et
        run: |
          if [ -f "rehber_durumu.csv" ]; then
            echo "Önceki veri başarıyla yüklendi"
            echo "cache-hit=true" >> $GITHUB_OUTPUT
          else
            echo "Önceki veri bulunamadı, yeni oluşturulacak"
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi
        id: check-cache

      - name: Dosyaları Listele (Cache Sonrası)
        run: ls -l

      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Betiği Çalıştır
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          CACHE_HIT: ${{ steps.check-cache.outputs.cache-hit }}
        run: python "MAU_Rehber - GITHUB.py"
