name: Personel Rehber Kontrolü

on:
  schedule:
    # Her gün sabah 09:00 (Türkiye saatiyle) çalışır.
    # 06:00 UTC = 09:00 TRT
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Bu satır, "Actions" sekmesinden manuel olarak çalıştırmanıza olanak tanır.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      # Önceki veriyi indirme adımı kaldırıldı.
      # - name: Önceki Veriyi İndir (Artifact)
      #   ...

      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Betiği Çalıştır
        id: script-run
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: python "MAU_Rehber - GITHUB.py"
      
      # Güncel veriyi yükleme adımı kaldırıldı.
      # - name: Güncel Veriyi Yükle (Artifact)
      #   ...
      
      - name: Hata Durumunda Teşhis Dosyalarını Yükle
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: hata-teshis-dosyalari
          path: |
            error_screenshot.png
            error_page_source.html
          if-no-files-found: ignore
