name: Personel Rehber Kontrolü

on:
  schedule:
    # Pazartesi-Cuma, sabah 09:00 (Türkiye saatiyle) çalışır (06:00 UTC)
    - cron: '0 6 * * 1-5'
    # Pazartesi-Cuma, sabah 10:40 (Türkiye saatiyle) çalışır (07:40 UTC)
    - cron: '40 7 * * 1-5'
    # Pazartesi-Cuma, akşam 18:00 (Türkiye saatiyle) çalışır (15:00 UTC)
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: Önceki Veriyi Cache'den Geri Yükle
        uses: actions/cache@v4
        id: personel-cache
        with:
          path: rehber_durumu.csv
          key: ${{ runner.os }}-personel-${{ hashFiles('mau_rehber.py') }}
          restore-keys: |
            ${{ runner.os }}-personel-

      - name: Cache Durumunu Kaydet
        id: cache-check
        run: |
          if [ -f "rehber_durumu.csv" ]; then
            echo "cache-hit=true" >> $GITHUB_OUTPUT
          else
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli Paketleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Betiği Çalıştır
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          CACHE_HIT: ${{ steps.cache-check.outputs.cache-hit }}
        run: python mau_rehber.py

      - name: Yeni Veriyi Cache'e Kaydet
        if: always()
        uses: actions/cache/save@v4
        with:
          path: rehber_durumu.csv
          key: ${{ runner.os }}-personel-${{ hashFiles('mau_rehber.py') }}
